{% set name = "django-stubs-ext" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-stubs-ext-{{ version }}.tar.gz
  sha256: 9a9ba9e2808737949de96a0fce8b054f12d38e461011d77ebc074ffe8c43dfcb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django
    - python >=3.6
    - typing-extensions

test:
  imports:
    - django_stubs_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/django-stubs
  dev_url: https://github.com/typeddjango/django-stubs/tree/master/django_stubs_ext
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
