{% set name = "django-stubs-ext" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 00c4ae307b538f5643af761a914c3f8e4e3f25f4e7c6d7098f1906c0d8f2aac9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - django
    - python >={{ python_min }}
    - typing_extensions

test:
  source_files:
    - tests
  imports:
    - django_stubs_ext
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/typeddjango/django-stubs
  dev_url: https://github.com/typeddjango/django-stubs/tree/master/django_stubs_ext
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
