{% set name = "django-stubs-ext" %}
{% set version = "5.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: db7364e4f50ae7e5360993dbd58a3a57ea4b2e7e5bab0fbd525ccdb3e7975d1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - django
    - python >=3.8
    - typing-extensions

test:
  source_files:
    - tests
  imports:
    - django_stubs_ext
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/typeddjango/django-stubs
  dev_url: https://github.com/typeddjango/django-stubs/tree/master/django_stubs_ext
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
