{% set name = "django-stubs-ext" %}
{% set version = "5.2.1" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fc0582cb3289306c43ce4a0a15af86922ce1dbec3c19eab80980ee70c04e0392

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - django
    - python >={{ python_min }}
    - typing_extensions

test:
  source_files:
    - tests
  imports:
    - django_stubs_ext
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/typeddjango/django-stubs
  dev_url: https://github.com/typeddjango/django-stubs/tree/master/ext
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
