schema_version: 1

context:
  name: django-stubs-ext
  version: "5.2.7"
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b690655bd4cb8a44ae57abb314e0995dc90414280db8f26fff0cb9fb367d1cac

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - django
    - python >=${{ python_min }}
    - typing_extensions

tests:
  - python:
      imports:
        - django_stubs_ext
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://github.com/typeddjango/django-stubs
  repository: https://github.com/typeddjango/django-stubs/tree/master/ext

extra:
  recipe-maintainers:
    - thewchan
