schema_version: 1

context:
  name: django-stubs-ext
  version: "6.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: ff21f7b4362928b56e18cda0595f296e33c665f3019f4e3e4231977385e76cac

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.11.0,<0.12.0
  run:
    - django
    - python >=${{ python_min }}
    - typing_extensions

tests:
  - python:
      imports:
        - django_stubs_ext
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.md
  homepage: https://github.com/typeddjango/django-stubs
  repository: https://github.com/typeddjango/django-stubs/tree/master/ext

extra:
  recipe-maintainers:
    - thewchan
